#version: '3.9'
services:
  # MySQL service
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my-app-network

  # Drupal service
  drupal:
    #image: my_app111
    build: 
      context: .
      dockerfile: Dockerfile.ubuntu
      #dockerfile: Dockerfile
    restart: always
    ports:
      - "81:80"
    environment:
      - DRUPAL_DATABASE_HOST=db
      - DRUPAL_DATABASE_PORT=3306
      - DRUPAL_DATABASE_NAME=${MYSQL_DATABASE}  # Use the same name from .env
      - DRUPAL_DATABASE_USER=${MYSQL_USER}  # Use the same name from .env
      - DRUPAL_DATABASE_PASSWORD=${MYSQL_PASSWORD}  # Use the same name from .env
      #- DRUPAL_TRUSTED_HOST: 'www\.example\.com'
      #https://www.drupal.org/docs/getting-started/installing-drupal/trusted-host-settings
    volumes:
      - drupal_data:/var/www/html
    networks:
      - my-app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  db_data:
    name: db_data
    driver: local
  drupal_data:
    name: drupal_data
    driver: local
    driver_opts:
      o: bind
      type: none
      device: drupal_data

networks:
  my-app-network:
    name: my-app-network
    driver: bridge
