#version: '3.9' --> getting error `version` is obsolete

services:
  # MySQL service
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my-app-network

  # Drupal service
  drupal:
    #image: my_app111
    build: 
      context: .
      #dockerfile: Dockerfile.ubuntu
      dockerfile: Dockerfile.ubuntu-multi
    restart: always
    ports:
      - "80"
    # ports:
    #   - "80:80"
    environment:
      - DRUPAL_DATABASE_HOST=db
      - DRUPAL_DATABASE_PORT=3306
      - DRUPAL_DATABASE_NAME=${MYSQL_DATABASE}
      - DRUPAL_DATABASE_USER=${MYSQL_USER}
      - DRUPAL_DATABASE_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - drupal_data:/var/www/html
      #- ./drupal_data:/var/www/html
    networks:
      - my-app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      replicas: 3  # Adjust the number of replicas as needed
      resources:
        limits:
          cpus: '0.5'  # Adjust CPU limit as needed
          memory: 512M  # Adjust memory limit as needed

  # Nginx service
  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Expose port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - drupal
    networks:
      - my-app-network

volumes:
  db_data:
    name: db_data
    driver: local
  drupal_data:
    name: drupal_data
    driver: local
    driver_opts:
      o: bind
      type: none
      device: drupal_data

networks:
  my-app-network:
    name: my-app-network
    driver: bridge
